export const SET_USER = 'SET_USER';
export const SET_USER_LOADING = 'SET_USER_LOADING';
export const SET_USER_LOGGED = 'SET_USER_LOGGED';
export const SET_USER_DATA = 'SET_USER_DATA';

export const SET_WRONG_USER_FIELD = 'SET_WRONG_USER_FIELD';

export const SET_WRONG_EMAIL_FIELD = 'SET_WRONG_EMAIL_FIELD';

export const ADD_NOTIFICATION = 'ADD_NOTIFICATION';
